#!/usr/bin/env bash
# Self-contained scientific reproduction entry point.
set -euo pipefail
cd "$(dirname "$0")"
export PYTHONDONTWRITEBYTECODE=1
export PYTHONUTF8=1

# Keep attempted runs separate from the retained scientific records. The caller
# may select a parent for raw attempts; no project file is rewritten or deleted.
if [[ -n "${WOC_CHECK_OUTPUT:-}" ]]; then
  mkdir -p "$WOC_CHECK_OUTPUT"
  tmp="$(mktemp -d "$WOC_CHECK_OUTPUT/run.XXXXXX")"
else
  tmp="$(mktemp -d)"
fi
printf 'Scientific run records: %s\n' "$tmp"
sha256sum -c raw/SHA256SUMS

if ! timeout --kill-after=10s 180s python3 -B -m unittest \
    tests.test_woc tests.test_witness_boundaries tests.test_directed_support \
    tests.test_index_boundaries tests.test_reproduction -v \
    > "$tmp/tests.stdout" 2> "$tmp/tests.stderr"; then
  cat "$tmp/tests.stdout"
  cat "$tmp/tests.stderr" >&2
  exit 1
fi

# Remove the nondeterministic wall-clock duration before freezing the transcript.
sed -E 's/^Ran ([0-9]+) tests in [0-9.]+s$/Ran \1 tests/' \
  "$tmp/tests.stderr" > "$tmp/tests.normalized.stderr"
{
  cat "$tmp/tests.normalized.stderr"
  printf '%s\n' 'DETERMINISTIC_SCIENTIFIC_REEXECUTION: PASS'
} > "$tmp/tests.frozen.stderr"

# Keep the retained 65-test transcript unchanged. Current implementation and
# source-binding regressions are mandatory, but have their own raw transcript.
if ! timeout --kill-after=10s 180s python3 -B -m unittest \
    tests.test_incident_pruning -v \
    > "$tmp/current-tests.stdout" 2> "$tmp/current-tests.stderr"; then
  cat "$tmp/current-tests.stdout"
  cat "$tmp/current-tests.stderr" >&2
  exit 1
fi

timeout --kill-after=10s 180s python3 -B src/run_all.py --out "$tmp/run1" > "$tmp/run1.stdout"
timeout --kill-after=10s 180s python3 -B src/run_all.py --out "$tmp/run2" > "$tmp/run2.stdout"

cmp -s "$tmp/run1.stdout" "$tmp/run2.stdout"
for path in raw/results.json generated/capacity_table.csv; do
  cmp "$tmp/run1/$path" "$tmp/run2/$path"
  cmp "$path" "$tmp/run1/$path"
done
# The archive remains bound to its original source. Fresh runs bind the current
# source separately; neither binding is regenerated by this verifier.
cmp "$tmp/run1/raw/run_manifest.json" "$tmp/run2/raw/run_manifest.json"
cmp current-source-manifest.json "$tmp/run1/raw/run_manifest.json"
cmp "$tmp/run1.stdout" raw/run_stdout.txt
cmp "$tmp/tests.frozen.stderr" raw/run_stderr.txt
sha256sum -c raw/SHA256SUMS

cat "$tmp/tests.stdout"
cat "$tmp/run2.stdout"
cat "$tmp/tests.frozen.stderr" >&2
cat "$tmp/current-tests.stdout"
cat "$tmp/current-tests.stderr" >&2
